### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by UnityCoderN** [AviralCoder/dicto#1]
hello ! You copied the para regarding the plagiarism from your computer book. Its plagiarism itself 👎

**Comment by AviralCoder** [comment]
Hi @UnityCoderN 
I hope you know the meaning of "Knowledge"
If I had even got the information from the computer book and pasted it here, what's with it? Its giving knowledge to use. If sharing phrases like this is really "plagiarism", then the whole world is literally doing plagiarism right now. Plagiarism doesn't mean that does it?
And if you don't really like it, then I can change the para.
Thanks
